spring:
  application:
    name: CodeForgeAI
  main:
    banner-mode: off
    web-application-type: none

  ai:
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: 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

      chat:
        options:
          model: llama-3.3-70b-versatile

logging:
  level:
    root: OFF